### ISSUE TITLE
OverflowMenu.svelte is always getting focused in its afterUpdate

### ISSUE THREAD

**Issue by mverdaguer** [IBM/carbon-components-svelte#191] opened 2020-06-15 11:05 UTC
As you can see in [its code](https://github.com/IBM/carbon-components-svelte/blob/master/src/components/OverflowMenu/OverflowMenu.svelte#L88), `OverflowMenu` is always `focusing` in the `afterUpdate` life-cycle.

The problem with it is that if you include this component inside any scroll container, whenever you refresh the page, this container will be auto-scrolled to the `OverflowMenu`. What's more, if you have a container including multiple `OverflowMenu` components, it will auto-scroll randomly depending on the last to be mounted.

You can test it using this code:

```!svelte
<script>
  import {
    OverflowMenu,
  } from 'carbon-components-svelte';

  const items = [
    { id: 1 },
    { id: 2 },
    { id: 3 },
    { id: 4 },
    { id: 5 },
    { id: 6 },
    { id: 7 },
    { id: 8 },
    { id: 9 },
    { id: 10 },
    { id: 11 },
    { id: 12 },
    { id: 13 },
    { id: 14 },
    { id: 15 },
  ];
</script>

<style>
  .body {
    height: 500px;
    width: 500px;
    overflow: hidden;
  }

  .list {
    height: 100%;
    overflow-y: auto;
  }

  .item {
    height: 100px;
    border: 2px solid black;
  }
</style>

<div class="body">
  <div class="list">
      {#each items as item, i}
        <div class="item">
          {item.id}
          <OverflowMenu flipped light />
        </div>
      {/each}
  </div>
</div>

```

Is there any specific reason for this behaviour?

**Comment by metonym** [comment] 2020-06-15 13:44
Thanks for raising this issue – will investigate.

**Comment by metonym** [comment] 2020-06-16 18:19
This is definitely a bug.

While the behavior of re-focusing the overflow button after closing the menu is correct, the behavior of focusing the button without having closed it is unintended.

**Comment by metonym** [comment] 2020-06-16 19:56
@mverdaguer A fix has been published in v0.7.3. Please upgrade and LMK if this resolves the issue.

**Comment by mverdaguer** [comment] 2020-06-17 13:37
@metonym I just tried it out and it works when you open the page. But if there is any `async` code within the same `component` that contains the `OverflowMenu` it will happen again whenever the `async` code updates the parent `component`.

You can try it out with this extended example:

```!svelte
<script>
  import { OverflowMenu, OverflowMenuItem } from 'carbon-components-svelte';

  const items = [
    { id: 1 },
    { id: 2 },
    { id: 3 },
    { id: 4 },
    { id: 5 },
    { id: 6 },
    { id: 7 },
    { id: 8 },
    { id: 9 },
    { id: 10 },
    { id: 11 },
    { id: 12 },
    { id: 13 },
    { id: 14 },
    { id: 15 },
  ];

  setTimeout(() => {
    items[2].title = 'title';
  }, 1000);
</script>

<style>
  .body {
    height: 500px;
    width: 500px;
    overflow: hidden;
  }

  .list {
    height: 100%;
    overflow-y: auto;
  }

  .item {
    height: 100px;
    border: 2px solid black;
  }
</style>

<div class="body">
  <div class="list">
    {#each items as item, i}
      <div class="item">
        {item.id}

        {#if item.title}
          <h1>{item.title}</h1>
        {/if}

        <OverflowMenu flipped light>
        <OverflowMenuItem>
          <div class="menu-item">
            <div>Download</div>
          </div>
        </OverflowMenuItem>
        </OverflowMenu>
      </div>
    {/each}
  </div>
</div>
```

Thanks for your time!

**Comment by metonym** [comment] 2020-06-17 13:40
In that case, the re-focus behavior must be triggered imperatively, instead of in the afterUpdate lifecycle method.

**Comment by mverdaguer** [comment] 2020-06-17 13:47
The problem is that the `async` code causes the `focus` in the `afterUpdate` to be called which shouldn't be called at all.

In the previous example, when `item.title` is set, the `OverflowMenu` will get focused, which shouldn't happen since it is not related at all.

**Comment by metonym** [comment] 2020-06-18 00:17
@mverdaguer An additional fix (#193) is shipped in 0.7.4.

**Comment by mverdaguer** [comment] 2020-06-18 08:18
Works like a charm. Thank's for your quick update!

**Comment by metonym** [comment] 2020-06-18 13:58
Great – the example code you provided to reproduce the bug was very helpful.

**Closed** 2020-07-19 19:40 UTC
Labels: bug
