### ISSUE TITLE
clipboard-copy causing problems in svelte kit

### ISSUE THREAD

**Issue by OG84** [IBM/carbon-components-svelte#669] opened 2021-06-05 09:04 UTC
with carbon-components-svelte@0.33.0 my svelte kit app fails with

```
ReferenceError: module is not defined
    at /node_modules/clipboard-copy/index.js?v=cb435601:4:1
```

As a workaround I had to add `clipboard-copy` to the optimizeDeps in svelte config.

```
const config = {
  preprocess: preprocess(),

  kit: {
    ...
    vite: {
      optimizeDeps: {
		include: ['clipboard-copy']
	},
      ...
    }
  }
};
```

**Comment by dendyswaran** [comment] 2021-06-05 12:29
thumbs up for @OG84 

for those who r still having issues when using a vanilla svelte + vite 2, you can adjust the vite.config.js as follow

`
export default defineConfig({
  plugins: [svelte()],
  optimizeDeps: {
    include: ['clipboard-copy']
  }
})`

**Comment by brunnerh** [comment] 2021-06-06 06:23
Duplicate of #598

**Closed** 2021-06-06 07:42 UTC

**Comment by metonym** [comment] 2021-07-05 21:02
It is no longer necessary to instruct vite to optimize `clipboard-copy` as of version 0.39.

The `clipboard-copy` dependency has been removed.

Instead, `CodeSnippet` and `CopyButton` use the native, asynchronous [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) to copy text. The functionality is exported as a prop so the user can override the behavior as needed.

**Note:** the `clipboard.writeText` API is not supported in IE 11 nor Safari iOS version 13.3 or lower. [caniuse](https://caniuse.com/mdn-api_clipboard_writetext) estimates that ~91% of global users use a browser compatible with the API.

### Overriding default copy behavior

Override the default functionality through the `copy` prop.

```svelte
<script>
  import copy from "clipboard-copy";
  import { CopyButton } from "carbon-components-svelte";
</script>

<CopyButton text="hello" copy={text => copy(text)} />
```

### Preventing default copy behavior

Pass a "no-op" empty function to prevent the component from copying text at all.

```svelte
<script>
  import { CopyButton } from "carbon-components-svelte";
</script>

<CopyButton text="hello" copy={() => {}} />
```
